### ISSUE TITLE
GA release

### ISSUE THREAD

**Issue by tedpennings** [salvoravida/redux-first-history#10]
When can we expect a GA release of this component?

Everything here seems very stable and reliable, so I'd love to see the package version reflect that. I'm excited to use it, and even more eager to use it without the `alpha` qualifier.

Thanks!

**Comment by salvoravida** [comment]
I'm sorry for the late release, anyway here it is!.

Enjoy and thank you for the feedback!

**Comment by tedpennings** [comment]
Yay thank you @salvoravida !
