### ISSUE TITLE
how to reset history?

### ISSUE THREAD

**Issue by dhcmega** [salvoravida/redux-first-history#109]
Hi!
When a user logs out, how can I reset history so it's not possible to go back to the home screen?
Thanks!

dhcmega

**Comment by salvoravida** [comment]
You should handle your home screen route with a isLogged check, and then redirect to /login if not.

**Comment by dhcmega** [comment]
Hi @salvoravida thanks for responding.

The logout case was just an example. 
I have a few cases in which I want to reset the history. For example when the user finishes a wizard that has steps.
I'm coming from connected-react-router which has a reset method. Do we have something similar?

Thanks again.
