### ISSUE TITLE
Cannot read properties of undefined (reading 'location')

### ISSUE THREAD

**Issue by eirin321** [salvoravida/redux-first-history#125]
Hi there,

It returns `Cannot read properties of undefined (reading 'location')` error if `combineReducers` is in another file.

CodeSandbox: https://codesandbox.io/p/sandbox/redux-first-history-demo-forked-h5w9x9?file=%2Fsrc%2Fstore.js%3A16%2C18

**Comment by SnomeaD** [comment]
Could it be that you didn't export your `routerReducer` from the ./store.js file ?

**Comment by salvoravida** [comment]
> Could it be that you didn't export your `routerReducer` from the ./store.js file ?

exactly https://codesandbox.io/p/sandbox/redux-first-history-demo-forked-dj6jn4?file=%2Fsrc%2Fstore.js
