### ISSUE TITLE
First LOCATION_CHANGE does not trigger saga

### ISSUE THREAD

**Issue by steinarb** [salvoravida/redux-first-history#126]
I use [a saga called locationSaga](https://github.com/steinarb/ukelonn/blob/master/ukelonn.web.frontend/src/main/frontend/sagas/locationSaga.js#L20) to listen to LOCATION_CHANGE and for each LOCATION_CHANGE, look at the path and decide what redux actions to fire off to start loading the data needed by that path.

This means that I can lazy-load the data needed for that path.

However this does not works for reloads.

The first redux action as seen in redux devtool is a LOCATION_CHANGE with path /ukelonn/users (the path reloaded on)
![image](https://github.com/salvoravida/redux-first-history/assets/691728/90ee1336-ae51-4965-8a30-ab962dbe314e)

However that LOCATION_CHANGE does not trigger [this saga](https://github.com/steinarb/ukelonn/blob/master/ukelonn.web.frontend/src/main/frontend/sagas/locationSaga.js#L20)

Navigating to a different page and navigating back, triggers the saga:
![image](https://github.com/salvoravida/redux-first-history/assets/691728/618c4673-aaa5-4e45-b816-36abb620b744)

One difference I can see is that the first LOCATION_CHANGE, the one that doesn't trigger the saga, is a pop() while the one that triggers the saga is a push()?

Or is it a timing related issue?

Should I have a saga that waits a couple of seconds and then fire off a push() to the current location?

**Comment by steinarb** [comment]
Versions from package.json:
```
        "@reduxjs/toolkit": "^2.2.3",
        "axios": "^1.6.8",
        "delay": "^6.0.0",
        "js-cookie": "^3.0.5",
        "qs": "^6.12.0",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-redux": "^9.1.0",
        "react-router-dom": "^6.22.3",
        "redux-first-history": "^5.2.0",
        "redux-saga": "^1.3.0",
```

**Comment by steinarb** [comment]
Turns out firing off a PUSH LOCATION_CHANGE to the current router location at the react app startup in index.js, was enough. https://github.com/steinarb/ukelonn/commit/dacca7669584278dd532c68a29f2fdaea4024c1f

The PUSH LOCATION_CHANGE was picked up by the locationChange saga, the propert path was detected and the necessary redux actions for data required by the current location were dispatched (on an app reload of the path).

But even though I now have a workaround, it is still interesting to me to understand why the pop LOCATION_CHANGE wasn't picked up by the saga?

**Comment by salvoravida** [comment]
I guess because your saga started after the first dispatch of the action, so the saga middleware was not yet loaded with your saga to propagate the action

**Comment by steinarb** [comment]
That sounds right.  The dispatch of a LOCATION_CHANGE (i.e. my workaround) is done _after_ I have set up the saga(s).

Thanks for responding! :smile:

**Comment by steinarb** [comment]
Nothing more to do here since there was a workaround, and since [sagas have been deprecated](https://www.reddit.com/r/reactjs/comments/1em8hc6/comment/lgy9pch/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) in favour of [RTK query](https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics) and [RTK listeners](https://redux.js.org/tutorials/essentials/part-6-performance-normalization#writing-reactive-logic), so closing this as not planned.
