### ISSUE TITLE
setState for exact route

### ISSUE THREAD

**Issue by daryaShashko** [salvoravida/redux-first-history#18]
I have a lot of cases when I need to change state for route. in react-navigation lib we have setParams for that, in histry api we have pushState() for that. Now I use replace without router, just with new state, but it`s not a good choice.
Can you provide the method for setState and getState

**Comment by salvoravida** [comment]
why do you need historyApi state in a Redux app ?!?

**Comment by salvoravida** [comment]
anyway you can use .replace("same-url", newState)
