### ISSUE TITLE
Remove TypeScript dependency on @reach/router

### ISSUE THREAD

**Issue by dbartholomae** [salvoravida/redux-first-history#19]
Thanks for the nice library! One thing on TypeScript: Currently the TypeScript definition file imports `@reach/router` which makes it a direct dependency and means I have to install that package even if I'm using `react-router`. It would be great if the dependency could be removed, at least from the file I have to consume :)

**Comment by salvoravida** [comment]
yeah you are right.
i have to move reachfy to "redux-first-history/reachfy" to do that, and it is a BC.

as i'm going to rewrite rfh in TS, i will do that into next v. 5.0

**Comment by salvoravida** [comment]
🎉  https://github.com/salvoravida/redux-first-history/releases/tag/v4.2.0

**Comment by dbartholomae** [comment]
Does it make sense to leave this ticket open until `5.x` is released?

**Comment by salvoravida** [comment]
I'm closing this issue, as of 5., reach router support will be removed. It has been merged with react router 6.x
