### ISSUE TITLE
Time Travel Does Not Effect Routes

### ISSUE THREAD

**Issue by aalpgiray** [salvoravida/redux-first-history#2]
I implemented this library alongside with [easy-peasy](https://github.com/ctrlplusb/easy-peasy). However, the URL changes when time travel has been applied, but Routers won't act to the change. 

Here is a SS: 
![image](https://user-images.githubusercontent.com/6337113/49499879-5166e400-f880-11e8-9df4-627e0b23c652.png)

If you wanna to give it a look. Here it is https://github.com/aalpgiray/easy-peasy-hooks

**Comment by salvoravida** [comment]
can you share more code here?

**Comment by salvoravida** [comment]
@aalpgiray can you try v.4.0.0-alpha.7 ?

let me know if it works.

**Comment by aalpgiray** [comment]
Thank you I close this one.
