### ISSUE TITLE
Feature Suggestion: add an optional `pathnameHistory` array to the `router` state

### ISSUE THREAD

**Issue by thisissami** [salvoravida/redux-first-history#20]
In an app I'm building, I needed to know the previous `url` to properly animate certain transitions. I've been using `redux-first-history` for many months now (thanks for maintaining this library!) and assumed that it would have a history array within the generated `reducer` state, given the name of the library - but it doesn't.

I've built a little `ContextProvider` for my own app using the `location: { pathname }` from `redux-first-history` that simply maintains the current pathname and the previous pathname. I think `redux-first-history` could become more useful to more people if it simply pushed the current `pathname` to a `pathnameHistory` array in the state (optionally enabled with a flag) every time the location changed (and `popped` the last `pathname` whenever a user goes back). Seems like something very simple to implement that could be useful for particular applications. :)

Or at the very least - some equivalent of `document.referrer` (which doesn't really exist in the context of a Single Page App) would go a long way.

I'm happy with my own `Context` centric solution, but I figured I'd share this thoughts here in case it resonated with anybody else. :)

**Comment by salvoravida** [comment]
hi! thank you for your idea!
maybe next release!

Just some ideas on how to implement it
```jsx

export const createReduxHistoryContext = ({
  history, 
  routerReducerKey = 'router', 
  oldLocationChangePayload = false, 
  reduxTravelling = false, 
  selectRouterState = null,
  rememberLocationChanges = 0  // activate with a maximum locationHistoryArray length
})

state.router = {
   previous: [ { location, action }, ....]   // length rememberLocationChanges 
   location : { pathname, search, hash, key}
   action : "PUSH" 
 }
```

**Comment by thisissami** [comment]
so there's 2 distinct approaches that could be taken - either:

`previous: [ { location, action }, ....]` as you've suggested above, or
`previous: [ location, ....]` - where when somebody goes "back" in their browser and the action is `POP`, that latest location is removed from the start of the array (i.e. `state.previous.shift()` if `state` were mutable)

Your suggestion has more data, which I think ultimately is better - as then the library is being unbiased about what is important - and the developer can decide what's important for their app.

**Comment by thisissami** [comment]
I would perhaps also change some of the names to be more clear / less ambiguous as follows:

`previous` ==> `previousLocations` 

`rememberLocationChanges` ==> `numberOfPreviousLocationsToTrack`, or if that's too verbose perhaps `numLocationChangesToTrack`

**Comment by salvoravida** [comment]
yes i agree on better names.

but i thought about storing all changes in queue not care about pop raplace or push. there is the "action" label. so the tracking is "raw".

on every LOCATION_CHANGE,
previous= [ newLocation, ...previouse.slice(0,numLocationChangesToTrack)]

**Comment by thisissami** [comment]
yes I agree that is a better approach. "raw" means that the developer decides what's important, not the library. and that is good.

**Comment by thisissami** [comment]
(and it is simpler to implement)

**Comment by salvoravida** [comment]
https://github.com/salvoravida/redux-first-history/releases/tag/v4.2.0

**Comment by thisissami** [comment]
wow I'm super impressed @salvoravida - that was super fast turnaround!! Especially considering you didn't receive any help in the form of a PR - I appreciate how quickly you responded to a feature request!!
