### ISSUE TITLE
add other value in the reducer & sync with window.history.location

### ISSUE THREAD

**Issue by younes0** [salvoravida/redux-first-history#21]
To save scroll position on route change, I was thinking of storing scrollPos in the `window.history.location.state`, but this wouldn't be synced with the RFH (redux first history) reducer. And in my understanding, adding data directly to the reducer on `LOCATION_STATE` action wouldn't affect `window.history.location.state`.
The neat way would be perhaps to override default behavior RFHto add data to its reducer, how can I do that   ?

Restoring scroll position is another matter and could be made directly in route component.

**Comment by younes0** [comment]
I solved my problem using: https://github.com/ipatate/react-router-scroll-memory

**Comment by salvoravida** [comment]
look here https://codesandbox.io/s/redux-first-history-demo-r3shw
```jsx
  <Link to={{ pathname: "/dashboard", state: "myState" }}>
```

console log
```
LOCATION_CHANGE {pathname: "/", search: "", hash: "", state: undefined, key: "x5p5h4"} PUSH
LOCATION_CHANGE {pathname: "/dashboard", state: "myState", search: "", hash: "", key: "ffquon"} PUSH
LOCATION_CHANGE {pathname: "/", search: "", hash: "", state: undefined, key: "1jg5ym"} PUSH
LOCATION_CHANGE {pathname: "/dashboard", search: "", hash: "", state: "myState", key: "ffquon"} POP
```

on POP (back button, you will have your previous state)
