### ISSUE TITLE
Reach Router Link component does not work when query string parameters are provided

### ISSUE THREAD

**Issue by saadtazi** [salvoravida/redux-first-history#24]
Hello,

First: thanks for the library.

I realized that, with reach-router, when `Link` reach-router component is used with query parameters (for example `<Link to="some/path?param1=value1">`), the browser url is properly updated but the Route component does not change and the redux router state is not updated (pathname, hash.

Here is a sandbox that reproduce the issue (copy of the repo example, trimmed to only keep reach related code, slightly modified to display the `window.location` and add query params to some urls): https://codesandbox.io/s/redux-first-history-demo-01tlt

You will be able to notice that, when clicking on the Link `Reach.Link to Dashboard?coucou=true#withhash`:
- the url gets updated (so window.location is fine) but the dashboard component does not get displayed 
- the store is not updated.

I cannot reproduce this issue with react-router (`search` is properly set in the redux store).

Also, here is a pure reach-router example that shows that it works well with query string parameters: https://codesandbox.io/s/reach-router-starter-v1-c7upk (the right component gets displayed when clicking on Link)

Note that I suspect the `navigate` method, generated by `reachify` [here](https://github.com/salvoravida/redux-first-history/blob/master/src/index.js#L18-L27) will not work when `to` param is a url with querystring parameters and a hash because only the `pathname` attribute is updated (might be related?).

Thank you

**Comment by salvoravida** [comment]
https://codesandbox.io/s/redux-first-history-demo-gzgox

it seems ok here

you have commented 
`  <Reach.LocationProvider history={reachHistory}>`

**Comment by saadtazi** [comment]
Thanks for the quick response.
OOps, I am so sorry: I tried so many things to understand an issue about  `search` not been properly updated when Link is used... That issue can be seen here: https://codesandbox.io/s/redux-first-history-demo-56jrr . When the Dashboard Link is clicked:
- `pathname` string contains the the path
- the search `search` remains empty when dashboard link is clicked.

I'll open a separate issue for that, probably later today.

Thank you again
