### ISSUE TITLE
reach-router: `search` store attribute not updated with `Reach.Link`

### ISSUE THREAD

**Issue by saadtazi** [salvoravida/redux-first-history#25]
Hello,

When a Reach.Link that contains querystring parameters is clicked:
- `pathname` string contains the path with the querystring (`search`) params
- the `search` remains empty 

That issue can be seen here: https://codesandbox.io/s/redux-first-history-demo-56jrr .

I suspect that it's because the `navigate()` method, generated by `reachify` [here](https://github.com/salvoravida/redux-first-history/blob/master/src/index.js#L18-L27) does not work when `to` param is a url with querystring parameters because only the `pathname` attribute is updated.

**Comment by salvoravida** [comment]
https://codesandbox.io/s/redux-first-history-demo-q63dx

fixed on release 4.2.6

**Comment by salvoravida** [comment]
@saadtazi let me know your feedback

**Comment by saadtazi** [comment]
That was so fast! It looks good! 👏 I updated the codesandbox.io so it uses the v4.2.6.
