### ISSUE TITLE
Accessing route paramaters

### ISSUE THREAD

**Issue by connorgiles** [salvoravida/redux-first-history#29]
What is the best way currently to extract matched parameters from the location state? With `connected-react-router` we can use `createMatchSelector` like this: 

`createMatchSelector({ path: '/jobs/:id' })(state)`. 

What is the best way to this currently with redux-first-history? Or should I use another dependency to extract params?

**Comment by connorgiles** [comment]
I ended up upgrading my `react-router-dom` package in order to use the new `useParams` like this:

`const { id } = useParams();`

Thanks!

**Comment by smagnetize** [comment]
I can't see the route params in the redux store. It would make sense to me, I tried this out specifically to get that data easily in the store.
