### ISSUE TITLE
Add support for React-Router v6.0.0-alpha.2

### ISSUE THREAD

**Issue by davirdasilva** [salvoravida/redux-first-history#30]
Hi,

Are you going to support the current alpha release (v2) of React-Router? Because everything seems to work but the page does not change. The action is dispatched with "@@router/LOCATION_CHANGE", pathname is correct and the browser URL changes, but it stays on the same page.

Thanks.

**Comment by salvoravida** [comment]
Of course. Can you provide a codesandbox?

**Comment by davirdasilva** [comment]
I made a simple sandbox. There are two buttons, if you press login you will dispatch a saga and inside this saga there is PUSH from redux-first-history. As you can see the URL changes but there is no navigation to the page. The second button is the `navigate` for React-Router v6 and it is working when clicked.

https://codesandbox.io/s/dazzling-borg-l8y2l

**Comment by salvoravida** [comment]
You have to use Router not BrowserRouter

**Comment by davirdasilva** [comment]
Perfect! Problem solved! Thanks.
