### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Avizura** [salvoravida/redux-first-history#35]
Hi, thanks for the library! Could you say why Link component and dispatch(push(path)) work differently as when you click on Link component the LOCATION_CHANGE action reaches middlewares before react-router sees the change (and performs rendering) and when dispatching action directly everything is vice versa? I have same issue with connected-react-router. Sorry if it's wrong place for the question.

**Comment by salvoravida** [comment]
https://github.com/salvoravida/redux-first-history#advanced-config

Try batch updates, should solve your problem

**Comment by Avizura** [comment]
Unfortunately did not help

**Comment by salvoravida** [comment]
> Unfortunately did not help

Hum, can you provide a code sand box with your code?

**Comment by Avizura** [comment]
Actually I can't... Apparently the problem is in my code. Appreciate your help!
