### ISSUE TITLE
Problem with goBack and goForward types

### ISSUE THREAD

**Issue by kfalkiewicz** [salvoravida/redux-first-history#43]
Hi
I have problem with usage of `goBack` and `goForward` functions. Both require argument, but probably they shouldn't. From my understanding `goBack()` should equal to `go(-1)`, and `goForward()` to `go(1)`. If I'm correct, then why both need an argument? What is point in having those methods?

Types for `goBack` and `goForward`
```tsx
export const goBack: (to: any) => ReduxAction;
export const goForward: (to: any) => ReduxAction;
```

**Comment by salvoravida** [comment]
yes you are right, it has been already fixed in future version 5.x

**Comment by kfalkiewicz** [comment]
@salvoravida Ok when we can expect a release of this version?

**Comment by salvoravida** [comment]
- rewritten in TS
- add support for react-router v6.0.0-beta.1

 ```tsx
import { HistoryRouter as Router } from "redux-first-history/rr6";
import { Route, Routes, Navigate } from "react-router-dom";
//...
import { store, history } from "./store";
//...

      <Router history={history}>
                  <Routes>
                    <Route path="/dashboard" element={<Dashboard />} />
                    <Route path="/" element={<Home />} />
                    <Route path="*" element={<Navigate to="/" />} />
                  </Routes>
      </Router>

 ```



demo rr6 here: https://codesandbox.io/s/redux-first-history-demo-rr6-uccuw
