### ISSUE TITLE
"TypeError: Cannot read property 'slice' of undefined" when setting savePreviousLocations to an integer value

### ISSUE THREAD

**Issue by Slapbox** [salvoravida/redux-first-history#46]
Using `react-router@5.2.x`:

```
 TypeError: Cannot read property 'slice' of undefined
    at routerReducer (webpack-internal:///./node_modules/redux-first-history/lib/index.esm.js:281:60)
    at combination (webpack-internal:///./node_modules/redux/es/redux.js:538:29)
```

`initialState.previousLocations` is an empty array, but it ends up unused and the state that is passed lacks the `previousLocations` key, which subsequently causes this fatal error.

-----

I'm also wondering what sort of data gets stored in `previousLocations` and how it relates to navigating `forward()`. Will `previousLocations` include entries that would be forward from the current location in the history stack?  Maybe a silly question, but unfortunately I haven't been able to test.

We're using `memoryHistory` - but I don't see any reason that should make a difference here. It all seems to work until we enable `savePreviousLocations`.

**Comment by salvoravida** [comment]
@Slapbox could you please provide a codesandbox example?

**Comment by Slapbox** [comment]
**Update:**

And actually after all that, perhaps all I needed to do was re-run `yarn`? I reapplied the stashed changes and re-ran `yarn` and so far I can't reproduce the error in our project.


----

**Original comment:** 

Thanks for your reply @salvoravida! I guess I can't without rebuilding large swathes of our setup, unfortunately. 

I did try, but did not succeed at reproducing it. If anyone else hits this and wants to take a shot at it, you can use this as a jumping off point: https://codesandbox.io/s/react-redux-demo-forked-j7ift

I'm guessing that we're somehow causing the state to be overwritten - but I just can't see where or how - or otherwise that perhaps one of our other Redux middlewares is interfering - perhaps [Electron Redux](https://github.com/klarna/electron-redux/tree/alpha) - although it should ignore any actions starting with `@@`.

I stashed away my work to come back to it, but if this error is unique to us then I guess it's going to stay stashed for a long time. I really hope someone has more insights into this eventually because I was really excited to implement this library! 

**This library is a great idea and great work @salvoravida!**

**Comment by salvoravida** [comment]
@Slapbox sounds good!

Maybe hot-reload did some mistake!

Regards!
