### ISSUE TITLE
The type of routerReducer becomes Reducer<any,AnyAction>.

### ISSUE THREAD

**Issue by uk-taniyama** [salvoravida/redux-first-history#51]
Therefore, the type of state becomes any.
I want the state type to be RouterState.

**Comment by salvoravida** [comment]
> Therefore, the type of state becomes any. I want the state type to be RouterState.

Hi @uk-taniyama, can you provide a codesandbox?

I suspect that you are talking about history v5.x where location state is any?

**Comment by salvoravida** [comment]
OK RouterState is missing I'm fixing it. which react router and history are you using?
v5 or v6?

**Comment by uk-taniyama** [comment]
I've added type parameters in various places.
I tried to make it possible to guess the type.

https://github.com/uk-taniyama/redux-first-history/commit/3f73044dccc744846d1eff3a918caeed59cf6e74

**Comment by uk-taniyama** [comment]
example

```
import { configureStore } from '@reduxjs/toolkit';
import { createBrowserHistory } from 'history';
import { createReduxHistoryContext } from 'redux-first-history';

interface MyState {
  hoge: string;
}

const history = createBrowserHistory();

const { routerReducer, routerMiddleware } = createReduxHistoryContext({ history });

const store = configureStore({
  reducer: {
    router: routerReducer,
  },
  middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(routerMiddleware),
});

type RootState = ReturnType<typeof store.getState>;
```
RootState as follows:
```
type RootState = {
    router: RouterState<unknown>;
}
```

**Comment by uk-taniyama** [comment]
I am using only history, not react router.

**Comment by salvoravida** [comment]
> I am using only history, not react router.

which version? v4 or v5 ?

**Comment by uk-taniyama** [comment]
"history": "^5.1.0",
    "redux-first-history": "^5.0.2",

**Comment by salvoravida** [comment]
> ```
> "history": "^5.1.0",
> "redux-first-history": "^5.0.2",
> ```

Hi thanks for your test, can you try 5.0.3 just released?

**Comment by salvoravida** [comment]
@uk-taniyama please note that LocationState is removed from history v5.x so redux-first-history v5.0.3, just released should work fine for you. lmk!

**Comment by salvoravida** [comment]
@uk-taniyama I will reopen this issue if 5.0.3 does not solve your issue. let me know

**Comment by uk-taniyama** [comment]
I installed it, and it showed up fine.
Thank you very much!
