### ISSUE TITLE
Issue in route if hash: null

### ISSUE THREAD

**Issue by sergeu90** [salvoravida/redux-first-history#53]
Hello. Good library a lot of thanks.

I have one question i used library https://github.com/mjrussell/redux-auth-wrapper#readme

 i have some code.

import { connectedReduxRedirect } from 'redux-auth-wrapper/history3/redirect';
import { push } from 'redux-first-history';

export const UserIsAuthenticated = connectedReduxRedirect({
  redirectPath: 'login',
  authenticatedSelector: (state) => !isEmpty(state.global.get('currentUser').toJS()),
  redirectAction: push,
  wrapperDisplayName: 'UserIsAuthenticated',
  allowRedirectBack: false,
});

but redirect to login route incorrect. I gettting loginnull instead login
I debugging code and i noticed. 
![image](https://user-images.githubusercontent.com/7217517/142026900-41d1f814-560c-40d4-8703-512f9ef4d787.png)
if hash: null then i have incorrect route. 
I checked if hash: undefined then all good.
Could you help me. Maybe i something understand.

**Comment by salvoravida** [comment]
@sergeu90 please can you provide a codesandbox?

history version? react-router version?

**Comment by sergeu90** [comment]
"history": "5.1.0",
 "react-router-dom": "6.0.2",

Sorry but sandbox i can't provide now.

**Comment by salvoravida** [comment]
the problem is with the history package:
https://github.com/remix-run/history/blob/main/packages/history/index.ts#L1052

null is not a valid value

**Comment by salvoravida** [comment]
@sergeu90 please open the issue on history repo

**Comment by sergeu90** [comment]
Thanks for quick reply.I think problem in redux-auth-wrapper. It send hash:null.

**Comment by sergeu90** [comment]
Thanks.Good research

**Comment by salvoravida** [comment]
@sergeu90 I opened an issue for that
