### ISSUE TITLE
No location change when using push from saga

### ISSUE THREAD

**Issue by dArignac** [salvoravida/redux-first-history#56]
Hi there,

first of all thanks for providing this package!

However, I have a small issue and I'm not sure if it my setup or anything else.
Following your docs I want to dispatch a location change from a saga (`use push action creator from redux-first-history if you need to dispatch location from saga or connected components.`). I'm using react-router v6.

```
# mysaga.ts
import { push } from "redux-first-history"
...

function* redirect() {
  yield put(push("/somewhere"))
}

function* watchSomething() {
  yield takeLatest(MyActionType.SOME_ACTION, redirect)
}

export function* mySaga() {
  yield all([
    fork(watchSomething)
  ])
}
```
The action is executed, but there is no redirect:

![image](https://user-images.githubusercontent.com/106409/143475747-7e63005e-b613-4b97-b7cf-4541fd5b9214.png)

Why does it behave this way? Hope you can shed a light, thanks!

Here is my store setup:

```
const { createReduxHistory, routerMiddleware, routerReducer } =
  createReduxHistoryContext({
    history: createBrowserHistory(),
  })

const sagaMiddleware = createSagaMiddleware()
const initialState = window.INITIAL_REDUX_STATE

export const store = createStore(
  combineReducers({
    authentication: authenticationReducer,
    employees: employeesReducer,
    layout: layoutReducer,
    router: routerReducer,
  }),
  initialState,
  composeWithDevTools(
    applyMiddleware(routerMiddleware),
    applyMiddleware(sagaMiddleware)
  )
)

sagaMiddleware.run(rootSaga)

export const history = createReduxHistory(store)
```

**Comment by salvoravida** [comment]
@dArignac 

are you using History Router as explained on README?

```
import React, { Component } from "react";
import { Provider, connect } from "react-redux";
import { HistoryRouter as Router } from "redux-first-history/rr6";
import { store, history } from "./store";

const App = () => (
      <Provider store={store}>
        <Router history={history}>
        //.....
        </Router>
      </Provider>
    );

export default App;

```

**Comment by dArignac** [comment]
HI @salvoravida , yes, my code looks the same.

**Comment by salvoravida** [comment]
Please look at the official example with rr6: https://codesandbox.io/s/redux-first-history-demo-rr6-uccuw

After that, provide a codesandbox with your case, otherwise I can't help .

**Comment by dArignac** [comment]
Hey @salvoravida,

I set up a codebox with a simplified application. Just navigate to its login page and click login. The saga calls the push back to the index page, but actually does not redirect. I guess I'm generally missing something or doing something wrong-

The saga emitting the push is here: https://codesandbox.io/s/webpack5-typescript-tsloader-redux-saga-05vo5?file=/ui/store/authentication/sagas.ts:317-342
The page itself (for reviewing with redux dev tools) is here: https://05vo5.sse.codesandbox.io/

Please note that the page does not reload automatically when code is changed.

Thanks a lot for your time!

**Comment by salvoravida** [comment]
@dArignac https://codesandbox.io/s/webpack5-typescript-tsloader-redux-saga-forked-hhcmt?file=/ui/store/index.ts:1004-1042

routerMiddlerware must be applied after saga one, otherwise can't intercept saga dispatched actions.

**Comment by dArignac** [comment]
Hi @salvoravida - you're right - thanks a lot! It is now working.
