### ISSUE TITLE
Does not work with redux-immutable

### ISSUE THREAD

**Issue by chadwatson** [salvoravida/redux-first-history#6]
Currently I get an error when trying to use this with [redux-immutable](https://github.com/gajus/redux-immutable) and react-router because it assumes that the redux state is an object literal instead of an Immutable collection.

What would you guys think about adding support for a selector in the options to select the router state?

```javascript
const {
  createReduxHistory,
  routerMiddleware,
  routerReducer
} = createReduxHistoryContext({
  history: createHistory(),
  selectRouterState: state => state.get("router")
});
```

**Comment by salvoravida** [comment]
done !

**Comment by JadowityHerbatnik** [comment]
Currently the `selectRouterState` is typed as 
```js
selectRouterState?: <S>(state: S) => RouterState
```
And using the snippet below I get a typescript error ```Property 'get' does not exist on type 'S'```.
```js
const { createReduxHistory, routerMiddleware, routerReducer } =
  createReduxHistoryContext({
    history: createBrowserHistory(),
    selectRouterState: (state) => state.get('router')
  });

```


So perhaps it's worth changing `selectRouterState` type to sth like:
```js
selectRouterState?: (state: RootState) => RouterState;
```
and call ```createReduxHistoryContext``` like this:
```js
  type RootState = typeof store.getState

  createReduxHistoryContext<RootState>({
    history: createBrowserHistory(),
    selectRouterState: (state) => state.get('router'),
  });
```

Just a first solution that came to my mind, hope to hear your thoughts!

**Comment by salvoravida** [comment]
Have you tried to explicit the State type?
```
const { createReduxHistory, routerMiddleware, routerReducer } =
  createReduxHistoryContext({
    history: createBrowserHistory(),
    selectRouterState: (state:YourRootState) => state.get('router')
  });
```

**Comment by JadowityHerbatnik** [comment]
> Have you tried to explicit the State type?
> 
> ```ts
> const { createReduxHistory, routerMiddleware, routerReducer } =
>   createReduxHistoryContext({
>     history: createBrowserHistory(),
>     selectRouterState: (state:YourRootState) => state.get('router')
>   });
> ```

Yes, I did. ```Type 'S' is not assignable to type 'YourRootState'```
Here's a minimal way to reproduce it:
```js
type Selector = <S>(state: S) => number;
type MyState = { id: number };

const mySelector: Selector = (state: MyState) => state.id;
```
Gives the following error:
```Type '(state: MyState) => number' is not assignable to type 'Selector'.
  Types of parameters 'state' and 'state' are incompatible.
    Type 'S' is not assignable to type 'MyState'.
