### ISSUE TITLE
Support `history` 5 types

### ISSUE THREAD

**Issue by flying-sheep** [salvoravida/redux-first-history#60]
`history` 5.1 renamed the type `LocationDescriptor` to [`To`](https://github.com/remix-run/history/blob/main/docs/api-reference.md#to). Since this project’s `push` and `replace` are typed like the following, their `location` argument is now typed as `any`. Current typing:

```ts
export declare const push: (location: import("history").LocationDescriptor<unknown>) => ReduxAction;
```

I think it can be fixed like this:

```ts
import { History, Location, Action } from 'history'
import { AnyAction as ReduxAction } from 'redux'

[...]

type To = Parameters<History['push']>[0]

declare const push: (to: To) => ReduxAction
[...]
```

**Comment by salvoravida** [comment]
@flying-sheep https://github.com/salvoravida/redux-first-history/releases/tag/v5.0.8

lmk!

**Comment by flying-sheep** [comment]
works wonderfully!
