### ISSUE TITLE
Is it possible to know if it's the first rendering?

### ISSUE THREAD

**Issue by danieldhp** [salvoravida/redux-first-history#66]
I'm migrating from `connected-react-router` and it has a feature that on the first rendering, the `LOCATION_CHANGE` action has a property named ` isFirstRendering` . Is there a feature similar to this?

Thanks

**Comment by salvoravida** [comment]
Hi @danieldhp , redux-first-history does not depend on react rendering lifecycle, it sync state with history since his creation, so there is no first render.

What's your use case?

**Comment by robations** [comment]
I was using this is a few places to detect actions that should only happen on first page load (loading data, authentication etc) but I managed to replace the behaviour by using (rxjs) `first()` operator and `skip(1)` to take or ignore the first location change action.
