### ISSUE TITLE
Feature request: support for custom reducer function

### ISSUE THREAD

**Issue by Slapbox** [salvoravida/redux-first-history#72]
I'm trying to upgrade our project to use this great library and I wonder if there's any plans/interest to implement an optional custom reducer function? The motivation for this would be to implement things like de-duplicating routes in the history stack, or removing routes which no longer exist.

Currently we do this via direct modifications on our `history` object when changing routes, but of course we won't be able to do that anymore if `redux` is the single source of truth.

**Comment by salvoravida** [comment]
Hi @Slapbox you can already use a custom Router Reducer:

```javascript
import { createStore, combineReducers, applyMiddleware } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";
import { createReduxHistoryContext, reachify } from "redux-first-history";
import { createWouterHook } from "redux-first-history/wouter";
import { createBrowserHistory } from 'history';

const { createReduxHistory, routerMiddleware } = createReduxHistoryContext({ 
  history: createBrowserHistory(),
  //other options if needed 
});

export const store = createStore(
  combineReducers({
    router: myCustomRouterReducer
    //... reducers //your reducers!
  }),
  composeWithDevTools(
    applyMiddleware(routerMiddleware)
  )
);

export const history = createReduxHistory(store);
//if you use @reach/router 
export const reachHistory = reachify(history);
//if you use wouter
export const wouterUseLocation = createWouterHook(history);
```

Of course, you must be sure that the reducer is returning a valid RouterState and an initial null state.
You could start by cloning the original one:
https://github.com/salvoravida/redux-first-history/blob/master/src/reducer.ts

**Comment by Slapbox** [comment]
Ah that's deceptively simple! Thank you for this great library!
