### ISSUE TITLE
window.location mismatch with redux router state location.

### ISSUE THREAD

**Issue by agarwal-nitesh** [salvoravida/redux-first-history#74]
React router version - 6.2.2
reudx-first-history version - 5.0.8
I have 3 routes: 
landing - / 
login - /login
signup - /signup

From landing, I navigate to login, if a user is not authorized using reduxFirsthistory.push. 
From login on clicking signup I navigate to signup using useNavigate. 
If I now goto the landing / path, I end up on signup. The redux router state location path is signup, whereas the window location path is / 

Thanks for the library, I am a little new to these concepts so it can be a major PEBCAK situation. I am able to reproduce it, though. At the same time, it might be, that this is how it's supposed to work.

**Comment by salvoravida** [comment]
Hi, can you provide a code sandbox example?

**Comment by agarwal-nitesh** [comment]
https://codesandbox.io/s/crazy-meadow-9urrru?file=/src/App.js

**Comment by salvoravida** [comment]
@agarwal-nitesh Sorry can't understand where is the problem. Can you describe the exact steps to reproduce?

**Comment by salvoravida** [comment]
@agarwal-nitesh  feel free to re-open as soon as the codesandbox is working
