### ISSUE TITLE
What about Server Side Rendering?

### ISSUE THREAD

**Issue by talkohavy** [salvoravida/redux-first-history#77]
Is it possible / will it be possible in the future
to use redux-first-history in server side render? (and how would you do it?)

Right now you have createBrowserHistory(),
but as you know, on the server doesn't have a DOM,
so it gives the natural error of:
`Error: Invariant failed: Browser history needs a DOM`

**Comment by salvoravida** [comment]
you should replace createBrowserHistory with createMemoryHistory
