### ISSUE TITLE
Cannot read properties of undefined (reading 'action')

### ISSUE THREAD

**Issue by seelasudheer99** [salvoravida/redux-first-history#78]
![image](https://user-images.githubusercontent.com/89505529/165493435-2a559f2b-e454-498c-9410-0880f2152856.png)

i followed the code in the documentation , but this error got popped up, any solution for this @Whazor @devzeebo @phlex89 @aalpgiray  @kurohune538

**Comment by salvoravida** [comment]
@seelasudheer99 please provide a codesandbox sample otherwise we cannot help you.
