### ISSUE TITLE
support "navigate" from @reach-router?

### ISSUE THREAD

**Issue by bassplayerch** [salvoravida/redux-first-history#8]
I couldn't find any example how to set this up with reach router.
Can you give me a simple example how to apply the reachify history to the reach router?

**Comment by ifyoumakeit** [comment]
Still working on this same issue, but they have a CodeSandbox with an example using Reach's LocationProvider.

https://codesandbox.io/s/wy5qw1125l

**Comment by salvoravida** [comment]
`javascript

            <div className="reachRouter">
              <h2>i'm a @reach/router subApp</h2>
              <Reach.LocationProvider history={reachHistory}>
                <React.Fragment>
                  <Reach.Link to="/">Reach.Link to Home</Reach.Link>
                  <Reach.Link to="dashboard">
                    Reach.Link to Dashboard
                  </Reach.Link>
                  <Reach.Link to="notExistRoute">
                    Reach.Link to notExistRoute and will be redirected to Home
                  </Reach.Link>
                  <Reach.Router>
                    <Home path="/" />
                    <Dashboard path="dashboard" />
                  </Reach.Router>
                </React.Fragment>
              </Reach.LocationProvider>
            </div>
`

**Comment by IMalyugin** [comment]
For those who want to integrate redux-first-history with @reach/router, I'll leave a comment here so you don't have to lose half a day trying to figure out how to make @reach/router navigate to work.

Tutorial for `redux-first-history` suggests initializing as follows:
```
import { createHistory } from 'history';
... = createReduxHistoryContext({ history: createHistory(window) });

Downsides of this approach is that @reach/router navigate uses globalHistory, which is exported by the package. Thus to make it work, we must use globalHistory instead of creating our own. But here's the problem: @reach/router globalHistory has slightly different interface than normal history. It can be fixed pretty easily tho, just wrap it via adapter that reverts interface.
```
import { globalHistory } from '@reach/router';

function reachHistoryAdapter (reachHistory) {
  const adaptedHistory = Object.create(reachHistory);
  adaptedHistory.listen = callback => reachHistory.listen((({ location }) => callback(location)));
  return adaptedHistory;
}

... = createReduxHistoryContext({ history: reachHistoryAdapter(globalHistory) });
```

CAUTION: There is no telling what other issues history inconsistencies may cause, but so far this seems like the only possible way of fixing things up. Especially since 'redux-first-history' `push` has different API than @reach/router navigate.

**Comment by salvoravida** [comment]
@IMalyugin thanks you for workaround on @reach/router navigate.
it would be better to use redux-first-history push action for imperative navigation, in a "redux-first" app.

anyway if someone would like to use "navigate" from @reach/router, your adapter seem to be fine.

i have pinned this issue

**Comment by salvoravida** [comment]
@bassplayerch @ifyoumakeit @IMalyugin 
https://github.com/salvoravida/redux-first-history/releases/tag/v4.5.0

**Comment by salvoravida** [comment]
@bassplayerch @ifyoumakeit @IMalyugin
can you test it please?
