### ISSUE TITLE
Missing @types/reach__router dependencie when using RFH with React-router

### ISSUE THREAD

**Issue by theFreedomBanana** [salvoravida/redux-first-history#82]
Hi,
Updating `react-router` from V5 to V6 I moved to `redux-first-history` because `connected-react-router` does not support `react-router` V6. I also updated `history` to v5 because it is the version used in `react-router` v6. But compiling I have the folowing issue with `redux-first-history` :
```
node_modules/redux-first-history/build/es6/actions.d.ts(9,19): error TS2315: Type 'Location' is not generic.
node_modules/redux-first-history/build/es6/create.d.ts(2,46): error TS7016: Could not find a declaration file for module '@reach/router'. '/opt/atlassian/pipelines/agent/build/code/node_modules/@reach/router/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/reach__router` if it exists or add a new declaration (.d.ts) file containing `declare module '@reach/router';`
node_modules/redux-first-history/build/es6/reachify.d.ts(1,41): error TS7016: Could not find a declaration file for module '@reach/router'. '/opt/atlassian/pipelines/agent/build/code/node_modules/@reach/router/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/reach__router` if it exists or add a new declaration (.d.ts) file containing `declare module '@reach/router';` 
```

I kinda find wierd that I would have to install types from another router to use RFH with `react-router`. But I probably missing something...
On the other hand Lcation type used to be generic but isn't anymore.

**Comment by salvoravida** [comment]
@theFreedomBanana  https://github.com/salvoravida/redux-first-history/releases/tag/v5.0.10

about the Location, the type is from your current history package. Are you sure have the correct package on your node modules?
have you uninstalled the old @types/history stuff?

**Comment by salvoravida** [comment]
lmk with v5.1.0

**Comment by salvoravida** [comment]
@theFreedomBanana https://github.com/salvoravida/redux-first-history/releases/tag/v5.0.11
lmk

**Comment by theFreedomBanana** [comment]
@salvoravida works like a charm! Thanks
