### ISSUE TITLE
state.router.location is not equal to useLocation()

### ISSUE THREAD

**Issue by SmoooZ** [salvoravida/redux-first-history#87]
The "Main Goal" section of redux-first-history describes that the following is always true:

`
//react-router v5 - v6
useLocation() === state.router.location
`

However a beta of react-router v6 did make sure that useLocation().pathname no longer includes the basename (see https://github.com/remix-run/react-router/releases/tag/v6.0.0-beta.5)
Therefore there is currently a mismatch between useLocation() and state.router.location ; the fact that state.router.location includes the basename does prevent the correct usage of react-router's matchPath() !
For example matchPath("/home", state.router.location.pathname) will always be false if a basename has been set.

**Comment by salvoravida** [comment]
@SmoooZ https://github.com/salvoravida/redux-first-history/issues/91#issuecomment-1237775167
use solution 2

**Comment by salvoravida** [comment]
https://github.com/salvoravida/redux-first-history/releases/tag/v5.1.0
