### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by phmatray** [salvoravida/redux-first-history#9]
Please consider support typescript for a seamless integration with easy-peasy.

**Comment by salvoravida** [comment]
yes i'm working on new version with immutableJs + typescript support.

hope i can release it before weekend.

:D

**Comment by phmatray** [comment]
It's really good to read.
I have just integrated redux-first-history into one of my projects and I hope to continue to see it evolve. :)

**Comment by ctrlplusb** [comment]
Awesome news @salvoravida 

Stoked to hear that this is on the way. 😊

**Comment by aalpgiray** [comment]
Any updates on that mate? I can take a look if you want.

**Comment by salvoravida** [comment]
should be done with 4.0.1 release (with merged prs)

Waiting for your feedbacks!

**Comment by salvoravida** [comment]
close.
feel free to re-open if there is any issue.
