### ISSUE TITLE
Redux Router state null + no events showing in Redux dev tool

### ISSUE THREAD

**Issue by sgnilreutr** [salvoravida/redux-first-history#90]
Issue:
1. The Redux router state only shows: location: null, action: null
2. The Router events are not showing in the Redux Devtools
3. BUT - navigation using dispatch(push()) is still working as expected.

I am yet to pinpoint the exact cause of the issue, but:

Running on:

redux-first-history: "5.0.12",
redux: "4.2.0",
react-router-dom: "6.3.0",
@reduxjs/toolkit: "1.8.3",
react: "18.2.0"

Store setup: https://github.com/Elysium-Labs-EU/juno-core/blob/dev/src/store/store.ts

**Comment by thanatusdev** [comment]
I have the same issue. Any solution to this?

**Comment by salvoravida** [comment]
@sgnilreutr you are using 2 instance of the store
https://github.com/Elysium-Labs-EU/juno-core/blob/f7e6c41520da80ab7fd95f49fdee56503318ec8d/src/store/store.ts#L51
https://github.com/Elysium-Labs-EU/juno-core/blob/dev/src/main.tsx#L28

the correct use is 
export const store =setupStore();
export const history = createReduxHistory(store);

import this store in the main app.
