### ISSUE TITLE
Remove react router basename from LOCATION_CHANGE redux action pathname

### ISSUE THREAD

**Issue by steinarb** [salvoravida/redux-first-history#91]
I would like the react router basename, if set, to be removed from payload.location.pathname in LOCATION_CHANGE redux actions created by router navigation.

I would also like push(LOCATION_CHANGE) to navigate to the correct place in the router, when the basename is omitted from payload.location.pathname.

This is related to https://github.com/salvoravida/redux-first-history/issues/87

**Comment by steinarb** [comment]
The reason for this, is because swipe navigation in this app https://github.com/steinarb/oldalbum broke after I upgraded to react v18/react router v6, which broke connected-react-router so I had to change to redux-first-history.

Everything seemed to work fine at first until I tried doing swipe navigation in chrome devtools simulated mobile phone setup.

Then navigation got a 404 because the basename was gone from the navigation URL.

I eventually traced this down to a change in history: https://github.com/remix-run/history/issues/810

Short story: basename was removed when going from history v4 to history v5 and it is not coming back (the reason is size: basename handling was the reason for 50% of history v4's code)

I can work around this for now by adding the basename in the path of LOCATI ON_CHANGE events sent with push() but it is messy.

I run multiple webapps in apache karaf on port 8181 on different web contexts and then I reverse proxy them through a DNS aliase.

E.g. I have http://localhost:8181/oldalbum and then I expose it out on the web as https://oldalbum.bang.priv.no

So the navigation code of the app needs to deal with both "/oldalbum" and "" at the start of the paths.

Previously this was done with setting the basename on the history, and then things just worked.

But that's no longer possible.

However react router v6 implements a basename, so if redux-first-history could hook into that it would be possible to get the magic back...?

**Comment by salvoravida** [comment]
Hi, can you create a codesandbox with a basic code sample?

**Comment by salvoravida** [comment]
OK, a couple of points
since guys at remix-run have dropped support for basename in history while supporting it only in react-router, there is nothing redux-first history can do internally, as it's just a bridge between them.
What you can do are 2 solution
1) https://github.com/remix-run/history/issues/810#issuecomment-824357551. (the ugly one)
2)https://github.com/remix-run/history/issues/810#issuecomment-733065089 (the pretty one)

**Comment by steinarb** [comment]
> OK, a couple of points since guys at remix-run have dropped support for basename in history while supporting it only in react-router, there is nothing redux-first history can do internally, as it's just a bridge between them. What you can do are 2 solution:

I was sort of hoping there were APIs on the react-router you could hook in to, but I guess if you're the bridge between the history and the react-router, there is, as you say, not much you can do..
 
> 1. [Where did `basename` go? [v5] remix-run/history#810 (comment)](https://github.com/remix-run/history/issues/810#issuecomment-824357551) (the ugly one)
> 2. [Where did `basename` go? [v5] remix-run/history#810 (comment)](https://github.com/remix-run/history/issues/810#issuecomment-733065089) (the pretty one)

Yes, I'm doing sort of 1 for now, as a workaround to get things working again.

None of the alternatives makes me happy. :-/

Things were so simple when basename was handled by the history, and now they are not.

One possibility would be to downgrade history to 4 and stay there for as long as it works...?

**Comment by steinarb** [comment]
@salvoravida A question: what if there was a redux store state value the basename could be read from?

Could that be leveraged by redux-first-history in some way, that would be not-too-hacky?

What I did was to

1. Calculate the basename from the URL the application was opened with and set that as the basename in the redux-router as well as save it to state.basename (this is in [oldalbum.web.frontend/src/main/frontend/src/index.js](https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6#diff-c1f942f4d09247d57da1d4347f54c39f6e9507e4eac9fca49632d5bc83911f53))
2. In the reducer for state.basename, set the basename if it is other than "/" which is set as the empty string (which is the default) [oldalbum.web.frontend/src/main/frontend/src/reducers/basenameReducer.js](https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6#diff-377e0682a8a0160f3634228c0d6fc88ac0131770107615d985c5ce92ecce9596)
3. In the components [Album.js](https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6#diff-f6d3814b9e1721a60c4c51063842a46850363bd5559c3c715333a133831858d7), [Picture.js](https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6#diff-19f904331984b659975025318e7b62b328941dcc6dff7708ff15a54fd28ea6e9) and [DeleteButton.js](https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6#diff-74987e2cd4b1d1bbcf013acb236b0b7933ac27b17b83b8878bad144bac916cd9) add "basename + " on all paths in dispatched push() actions
4. In [locationSaga.js](https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6#diff-3905c5646fa1bbaa762f27a7dc86888d0e11c53f4a238a985c748b7163ad9a18), which triggers load actions on when entering certain router locations, add "basename + " on all paths tested against the location
5. In [albumSaga.js](https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6#diff-70c8eae8f864cb45d3d0e7676b4ed75a16f9905e78de3fbf2a95699c740bda1e) and [pictureSaga.js](https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6#diff-1fc37965cd47760050a52ae839f861075521784111a248d523b982b0560ab810) add "basename + " to the paths sent to push() actions

It would be really neat if I was able to lose "basename + " from the sagas and components! Really, really neat!

The full change is here: https://github.com/steinarb/oldalbum/commit/a52ae72f6abaa097f32e31a46f28f0d7b09a1cc6

**Comment by salvoravida** [comment]
@steinarb https://github.com/salvoravida/redux-first-history/releases/tag/v5.1.0
lmk

**Comment by steinarb** [comment]
My app greatly simplified! Thank you! https://github.com/steinarb/oldalbum/commit/4d2c704cf5f1068912015f23356748aa9ecf073d
