### ISSUE TITLE
query params

### ISSUE THREAD

**Issue by Kost927** [salvoravida/redux-first-history#93]
In the "connected-react-router" I could get query params from the "state.router.location.query",  but here I can see only search params, any chance I can get query from the state.router.location object? It is much easier to have them in redux, than use "new URLSearchParams" and "searchParams.get()"

**Comment by salvoravida** [comment]
what's wrong with https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/entries ?

Can you explain your use case?

**Comment by salvoravida** [comment]
@Kost927
