### ISSUE TITLE
History V4 support

### ISSUE THREAD

**Issue by DRichter-r** [salvoravida/redux-first-history#94]
Hi! 
We´re still using history V4.10.1 because of other dependencies. With the newest update to redux-first-history 5.1.1. it seems like the support for history V4 broke. 
The Error is:  error TS2339: Property 'back' does not exist on type 'History<unknown>'.
Can you recreate this behavior? 

Best wishes, 
Daniel.

**Comment by salvoravida** [comment]
@DRichter-r can you add a codesandbox example?

**Comment by DRichter-r** [comment]
Here´s a repo where the error is reproduced: [https://github.com/ceisele-r/redux-first-history-tsc-repro.git](https://github.com/ceisele-r/redux-first-history-tsc-repro.git)
with this [Error](https://github.com/ceisele-r/redux-first-history-tsc-repro/actions/runs/3060591340/jobs/4939291075#step:5:9)

The issue might be that @types/react-router and @types/react-router-dom pull @types/history v4.7.11 as depencies.

**Comment by salvoravida** [comment]
you have to use   "skipLibCheck": true, that's because rfh support both v4/v5
