### ISSUE TITLE
Can't make it work properly with react-router v6

### ISSUE THREAD

**Issue by matteo-dirollo** [salvoravida/redux-first-history#98]
I'm using { BrowserRouter } to navigate on my webapp, the only problem with v6 and BrowserRouter is that it doesn't support this :

import { HistoryRouter as Router } from "redux-first-history/rr6";

Of course I can not use them together but the real issue is that BrowserRouter doesn't track the location when I'm changing the url and HistoryRouter doesn't work well with Routes and Route components of react-router v6 and I can't really use it at the place of { BrowserRouter } from 'react-router-dom';

**Comment by salvoravida** [comment]
react router version ?

**Comment by matteo-dirollo** [comment]
"react-router-dom": "^6.3.0",

**Comment by matteo-dirollo** [comment]
is there any example to make it work properly with this version? When I I change page redux doesn't store the new location in my state, if check it out the location is randomly picked idk why

**Comment by salvoravida** [comment]
https://codesandbox.io/s/redux-first-history-demo-rr6-forked-olmbbo
